---
- include_role:
    name: andrewrothstein.unarchive-deps
- include_role:
    name: andrewrothstein.gcc-toolbox
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: install dep pkgs...
  become: true
  become_user: root
  with_items: '{{ cntlm_dep_pkgs | default([]) }}'
  package:
    name: '{{ item }}'
    state: present

- name: downloading {{ cntlm_tgz_url }} to {{ cntlm_tmp_tgz }}
  become: true
  become_user: root
  get_url:
    url: '{{ cntlm_tgz_url }}'
    dest: '{{ cntlm_tmp_tgz }}'
    checksum: '{{ cntlm_checksum }}'
    mode: 0644

- name: unarchiving {{ cntlm_tmp_tgz }} to {{ cntlm_src_parent_dir }}
  become: true
  become_user: root
  unarchive:
    remote_src: true
    src: '{{ cntlm_tmp_tgz }}'
    dest: '{{ cntlm_src_parent_dir }}'
    creates: '{{ cntlm_src_dir }}'

- name: build...
  become: true
  become_user: root
  with_items:
    - '{{ cntlm_src_dir }}/configure'
    - make
    - make install
  command: '{{ item }}'
  args:
    chdir: '{{ cntlm_src_dir }}'

- name: cleanup...
  become: true
  become_user: root
  file:
    path: '{{ cntlm_src_dir }}'
    state: absent
