---
- name: resolve platform specific vars
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'

- name: install dep pkgs...
  become: yes
  become_user: root
  with_items: '{{cntlm_dep_pkgs|default([])}}'
  package:
    name: '{{item}}'
    state: present

- name: download src...
  become: yes
  become_user: root
  get_url:
    url: '{{cntlm_tgz_url}}'
    dest: /tmp/{{cntlm_tgz}}
    checksum: '{{cntlm_checksum}}'
    mode: 0644

- name: unarchive
  become: yes
  become_user: root
  unarchive:
    src: /tmp/{{cntlm_tgz}}
    dest: '{{cntlm_src_parent_dir}}'
    creates: '{{cntlm_src_dir}}'

- name: build...
  become: yes
  become_user: root
  with_items:
    - ./configure
    - make
    - make install
  command: '{{item}}'
  args:
    chdir: '{{cntlm_src_dir}}'

- name: cleanup...
  become: yes
  become_user: root
  file:
    path: '{{cntlm_src_dir}}'
    state: absent
